### ISSUE TITLE
Have you tried directly train the network on segmentation task?

### ISSUE THREAD

**Issue by Cugtyt** [ashaw596/squeezenas#3]
Hi, I noticed you pretrain model on ImageNet and COCO, and finaly cityscapes, have you tried directly train the model on cityscapes, or pascal voc dataset. Or this is harder to achieve a good performance? Could you give more explanation?

**Comment by ashaw596** [comment]
Hi! So we mostly did this pre-training to stay inline with some other baselines, and then continued using this standardized pipeline for comparability. We haven't done too much work, though we would like to try it. Very preliminary work we tried months ago seemed to achieve lower performance, but we trained for low number of epochs. Some literature seems to show that you can get good results without pre-training by training the network for many more epochs on Cityscapes.

**Comment by Cugtyt** [comment]
Thanks, looking forward your training code. :-)
